### ISSUE TITLE
Sylius 1.11 compatibility ?

### ISSUE THREAD

**Issue by H4Mm3r** [SyliusCrafts/BootstrapTheme#102]
Hello,

Not compatible with Sylius 1.11 ?

> $ composer require sylius/bootstrap-theme
> Info from https://repo.packagist.org: #StandWithUkraine
> Using version ^0.4.0 for sylius/bootstrap-theme
> ./composer.json has been updated
> Running composer update sylius/bootstrap-theme
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires sylius/bootstrap-theme ^0.4.0 -> satisfiable by sylius/bootstrap-theme[v0.4.0].
>     - sylius/bootstrap-theme v0.4.0 requires sylius/sylius ~1.8.0 || ~1.9.0 || ~1.10.0 -> found sylius/sylius[v1.8.0, ..., v1.10.13] but it conflicts with your root composer.json require (^1.11).
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require sylius/bootstrap-theme:*" to figure out if any version is installable, or "composer require sylius/bootstrap-theme:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by nfacciolo** [comment]
When this theme should be compatible with 1.11 ?

**Comment by oallain** [comment]
Done on [ tag v0.5.0](https://github.com/SyliusCrafts/BootstrapTheme/releases/tag/v0.5.0)

**Comment by H4Mm3r** [comment]
composer require is now working, but on a clean Sylius 1.11.7 install, running it give an error after a refresh :

`An exception has been thrown during the rendering of a template ("Asset manifest file "/opt/sylius/dev/public/build/manifest.json" does not exist. Did you forget to build the assets with npm or yarn?").`

Thanks to this doc : https://docs.sylius.com/en/latest/book/themes/bootstrap-theme.html mentioned on this repository main page. The first point is not working.

Thanks by advance.
