### ISSUE TITLE
Sylius 1.12 compatibility

### ISSUE THREAD

**Issue by ayman-benmada** [SyliusCrafts/BootstrapTheme#106]
Hello, the bootstrap child theme did not work on sylius 1.12

I followed the documentary https://docs.sylius.com/en/latest/book/themes/bootstrap-theme.html but not working.

I have the default theme even if in the debugger we can see that it is the child theme.

**Comment by H4Mm3r** [comment]
Same need here.

`  Problem 1
    - Root composer.json requires sylius/bootstrap-theme ^0.5.0 -> satisfiable by sylius/bootstrap-theme[v0.5.0].
    - sylius/bootstrap-theme v0.5.0 requires sylius/sylius ~1.8.0 || ~1.9.0 || ~1.10.0 || ~1.11.0 -> found sylius/sylius[v1.8.0-RC.1, ..., 1.11.x-dev] but it conflicts with your root composer.json require (^1.12).`

Is this project abandoned ?

Thanks by advance

**Comment by nicolastiran** [comment]
any news ?

**Comment by oallain** [comment]
If you have any time you can to make a pull request to fix it.
