### ISSUE TITLE
Render is not same screenshot

### ISSUE THREAD

**Issue by Sophikitis** [SyliusCrafts/BootstrapTheme#108]
Hi everyone,

I'm trying to install the bootstrap theme on a new sylius 1.10 project but I can't get the same rendering as on the repository screenshot.
I also have problems with the buttons or menus, when I click on them, nothing happens

https://github.com/SyliusCrafts/BootstrapTheme#screenshots

I have the impression to be the only one to have this problem.

![image](https://user-images.githubusercontent.com/33518344/209428563-97ff089e-f1d4-4b32-9668-29f028764f94.jpeg)![image](https://user-images.githubusercontent.com/33518344/209428567-c350c840-335d-41cf-b3e0-61e09930d1e7.jpeg)![image](https://user-images.githubusercontent.com/33518344/209428570-17a745e9-ce80-4e47-b3ac-fdbd4767af8e.jpeg)

**Comment by oallain** [comment]
Hello @Sophikitis 

IMHO start a project with Sylius 1.10 now, it's not a good idea, this version is outdated as you can see on [Release page](https://docs.sylius.com/en/1.12/book/organization/release-cycle.html#supported-versions).

For the shifts of visuals, it is quite possible, Sylius makes changes regularly. The captures are not necessarily up to date.

**Comment by Sophikitis** [comment]
Hi! 

Thanks for your answer.
I'm installing version 1.10 because my company hasn't migrated to php8 yet. We are still on php7.4.

Concerning the theme it is stipulated that it is compatible until version 1.11 if I understood correctly? 

And even if I do not take in consideration the screenshots of the repo, I see that some elements are misplaced as if it was missing css. And the buttons don't work... 

Unfortunately, I can't find any video content that explains or shows the theme installation.

But I have a small question, do you know which version of bootstrap is used for the theme?

Thanks in advance

**Comment by oallain** [comment]
Hi,

I found [bootstrap: ^4.5.0](https://github.com/SyliusCrafts/BootstrapTheme/blob/master/tests/Application/package.json#L20) in this repo.

**Comment by Sophikitis** [comment]
Hi,

My problem is solved, it's a problem of bootstrap version. I followed the documentation of sylius which does not specify the version of bootstrap to install.

I had bootstrap 5 and boostrap native 4 and in the repository documentation it says :

yarn add bootstrap@^4.5.0 bootstrap.native@^3.0.0


After using the right version the theme works correctly.
It might be useful to clarify this on the official website of Sylius
