### ISSUE TITLE
Issue in AddressBook/index.html.twig template

### ISSUE THREAD

**Issue by olia-bn** [SyliusCrafts/BootstrapTheme#111]
Line 36 (for loop) doesn't seem correct, the if should probably be a separate statement or make use of `|filter` like Sylius default theme does:

```
{% for address in addresses if default_address is null or address.id != default_address.id %}
    <div class="col-12 col-lg-6 mb-3" id="sylius-addresses" {{ sylius_test_html_attribute('addresses') }}>
        {% include '@SyliusShop/Account/AddressBook/_item.html.twig' %}
    </div>
{% endfor %}
```

Above gives the following error:
```
Unexpected token "name" of value "if" ("end of statement block" expected).
```

**Comment by oallain** [comment]
Hello,

Fixed in [v1.0.0](https://github.com/SyliusCrafts/BootstrapTheme/releases/tag/v1.0.0)

If you still have the problem, you can re-open this issue.
