### ISSUE TITLE
Changing primary theme colors

### ISSUE THREAD

**Issue by brianmituka** [SyliusCrafts/BootstrapTheme#123]
I would like to update the default primary colors from teal to yellow, but I've tried overriding the variables in a new scss file and importing it to the main.scss, cleared the cache but it's not taking effect is there a clear way of changing the default colors from teal to something else?

**Comment by oallain** [comment]
Hello,

Have you try yarn watch?

**Comment by brianmituka** [comment]
Yes. I have tried that but it seems the changes are being overwritten

**Comment by brianmituka** [comment]
Opted to change the primary colour in the` _variables.scss`  file under scss-utils

**Comment by tejac** [comment]
@brianmituka could you share in detail what exactly you did? I'm facing the same challenge. As per the docs, I have added a _varriables.scss file with $primary definition and imported it at the beginning of index.scss, but no change.
