### ISSUE TITLE
Release for Sylius 1.7

### ISSUE THREAD

**Issue by 4c0n** [SyliusCrafts/BootstrapTheme#50]
The README states that we can use the master branch for Sylius 1.7 installations. However I'd prefer not to use `dev-master` as a version constraint.

Could perhaps an alpha or beta be released for 1.7? Or could we open a `1.0` branch until then?

Otherwise what needs to be done before we can have a release for Sylius 1.7?

**Comment by toofff** [comment]
@pocky it would be interesting to output an alpha, are there still things to correct?

**Comment by giosh94mhz** [comment]
Don't want to be rude, but yes a minor composer release would be nice.

You may add ` "conflict": { "sylius/shop-bundle": "<1.7" } ` to a new 0.1.3, and then add a simple 0.2.0 on master; this will prevent the wrong version to be installed.
