### ISSUE TITLE
js error on checkout address step page when user is logged in

### ISSUE THREAD

**Issue by htaoufikallah** [SyliusCrafts/BootstrapTheme#74]
If user is logged in or went back to address step from other checkout steps he got this error which break the page so it render the shipping address form although the sylius_checkout_address_differentShippingAddress is not checked

```
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at SyliusApiToggle (sylius-api-toggle.js:17)
```

**Comment by oallain** [comment]
Hello,

This issue seems to be outdated. If it isn't, feel free to reopen it.
