### ISSUE TITLE
Is 'data-loading' attribute used ?

### ISSUE THREAD

**Issue by ehibes** [SyliusCrafts/BootstrapTheme#80]
Hi,

I see 'data-loading' attribute is added to province field, but nothing happens... Is it the normal behavior ?

https://github.com/Sylius/BootstrapTheme/blob/c057ce6d421cddaab56e77c69ffcdd99c9367ed5/assets/js/sylius-province-field.js#L40

**Comment by oallain** [comment]
Hello,

This issue seems to be outdated. If it isn't, feel free to reopen it.
