### ISSUE TITLE
Revert: Fix missing original price macro

### ISSUE THREAD

**Issue by pocky** [SyliusCrafts/BootstrapTheme#92]
Hello,

https://github.com/SyliusCrafts/BootstrapTheme/pull/89 from @maxperei) was reverted because of this error
`Unknown "sylius_calculate_original_price" filter. Did you mean "sylius_caculate_price" ?`

**Comment by maxperei** [comment]
hi @pocky,
`caculate` are u sure ?
you can revert if you want
